### ISSUE TITLE
삭메에 isPhoto하면 false나옴

### ISSUE THREAD

**Issue by taeseong14** [NyangBotLab/DBManager_deploy#1]
ㅇㅇ
![a](https://user-images.githubusercontent.com/88077395/222913405-0752603e-bbe1-4c9e-9ab5-83dc8123ea3f.png)
![b](https://user-images.githubusercontent.com/88077395/222913408-1c5e0988-1439-416e-8be1-0290bf546dd3.png)

**Comment by saroro1** [comment]
수정됨
