### ISSUE TITLE
[BUG] 카카오톡 10.4.2 버전에서 이슈발생

### ISSUE THREAD

**Issue by jaehyun1122** [NyangBotLab/DBManager_deploy#10]
### 설명:
스크립트를 컴파일 했을때 다음과 같이 오류가 발생하고 작동하지 않음

Runtime Error(kakao_DB)
Wrapped android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 522 SQLITE_IOERR_SHORT_READ): , while compiling: PRAGMA journal_mode (file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/DBManager/DBManager.js#1)	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/DBManager/DBManager.js:1 (O)
	at
file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/DBManager/DBManager.js:1

### 환경:
윈도우11/녹스앱플레이어
- OS: 안드로이드 9
- 메봇/채자봇: 메봇
- 메봇 버전: 0.7.29a/92
- 모듈 버전: 2.4.2

### 기타:
카카오톡 10.4.2버전 사용하는 여러기기에서 같은 오류가 납니다.

**Comment by vientorepublic** [comment]
DB가 깨진 것 같은데, 카카오톡 DB를 삭제하고 스크립트를 리로드 해보시겠어요?

**Comment by jaehyun1122** [comment]
모듈 버전을 다운그레이드 시키고 카톡버전을 10.3.8로 다운그레이드 시켰는데 잘 작동합니다
2.4.2버전에 카톡 10.3.8버전을 사용할때만 안되는것 같은데 우연일까요

**Comment by saroro1** [comment]
전 잘 되는데 애뮬레이터 문제 아닐까요?

**Comment by saroro1** [comment]
@jaehyun1122 

직접 카카오톡 모든 방에 한번씩 들어갔다오면 해결될거에요. 암호화 변경된 걸 처리해야 합니다. 다 되고 안되시면 답글 달아주세요.

**Comment by saroro1** [comment]
#11 


확인 요망

**Comment by jaehyun1122** [comment]
해결됨
