### ISSUE TITLE
[BUG] <카카오톡 10.4.2 에러 발생>

### ISSUE THREAD

**Issue by Airweed** [NyangBotLab/DBManager_deploy#11]
### 현재 동작:
채팅 수신 시 에러

### 재현 방법:

컴파일은 정상 작동
채팅방에서 아무 메시지 수신 할 때마다
javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/utils/decrypt/decrypt.js:1
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/utils/mapper/mapper.js:1 (R)
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/utils/mapper/mapper.js:1
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/utils/mapper/mapper.js:1 (q)
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/utils/mapper/mapper.js:1
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/utils/mapper/mapper.js:1
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/utils/db_util/src/db_utils.js:1
	at file:/storage/emulated/0/Airbot/Bots/Airbot/modules/DBManager/DBManager/DBManager.js:1

에러가 4개씩 발생

### 환경:
- OS: 안드로이드 8
- 메봇/채자봇: 메봇
- 메봇 버전: 0.7.29a/92
- 모듈 버전: 2.4.2

**Comment by naijun0403** [comment]
카카오톡 버전이 뭔가요?

**Comment by saroro1** [comment]
직접 카카오톡 모든 방에 한번씩 들어갔다오면 해결될거에요. 암호화 변경된 걸 처리해야 합니다. 다 되고 안되시면 답글 달아주세요

**Comment by Airweed** [comment]
아 모든 방을 안 열어봐서 생기는 오류였네요 감사합니다
