### ISSUE TITLE
[Feature request] 공감기능 불러오기

### ISSUE THREAD

**Issue by HingguMaster** [NyangBotLab/DBManager_deploy#14]
**기능 제안**
카카오톡에는 메시지마다 좋아요를 누르는 느낌의 공감 기능이 있습니다. 가능한지는 모르나 만일 가능하다면 이것에 대한 정보를 Chat의 Accessor로 추가하면 좋을 것 같습니다.

**Comment by HingguMaster** [comment]
![image](https://github.com/NyangBotLab/DBManager_deploy/assets/161094351/9d078869-9eb3-46b2-9753-5cb40de8035d)
이 기능을 말하는 것입니다

**Comment by saroro1** [comment]
> ![image](https://github.com/NyangBotLab/DBManager_deploy/assets/161094351/9d078869-9eb3-46b2-9753-5cb40de8035d)
> 이 기능을 말하는 것입니다

공감기능은 http요청이며 타인이 정지당한 선례가 있기 때문에 추가 하지 않을 계획입니다

**Comment by naijun0403** [comment]
wont fix
