### ISSUE TITLE
이슈까진 아닌데 isAudio => isFile?로 바꾸면 조을듯

### ISSUE THREAD

**Issue by taeseong14** [NyangBotLab/DBManager_deploy#2]
파일(zip 등등)이 똑같이 type 18이라 isAudio가 true나옴ㅉ
![a](https://user-images.githubusercontent.com/88077395/222927204-360a733c-32d7-44fb-9629-ec9f518c9bc5.png)
![b](https://user-images.githubusercontent.com/88077395/222927200-b3bf1545-daad-43e1-a259-01a9618b2cc5.png)
![c](https://user-images.githubusercontent.com/88077395/222927209-35974355-7583-4dee-a7fc-f52e7e2d24d0.png)

**Comment by saroro1** [comment]
attachment로 구분하게 하겠습니다. 다음 버전에 isFile is Audio 구분 예정

**Comment by saroro1** [comment]
수정 완료 isFile, isMap, isAudio로 구분
