### ISSUE TITLE
삭메 deleteTime null나옴

### ISSUE THREAD

**Issue by taeseong14** [NyangBotLab/DBManager_deploy#3]
제곧내
![aa](https://user-images.githubusercontent.com/88077395/222931619-302b1ed8-4cd6-4f00-a105-f9f7b57db840.png)
![bb](https://user-images.githubusercontent.com/88077395/222931620-f61e8e76-a9dd-458f-a725-c7a26f48aacb.png)

**Comment by taeseong14** [comment]
참고))) ru = replied > underchat

**Comment by saroro1** [comment]
메소드 삭제 예정

**Comment by saroro1** [comment]
아무튼 벽오동나무가 잘못했네요

**Comment by saroro1** [comment]
벽오동나무가 잘못함
