### ISSUE TITLE
녹스와 같은 에뮬레이터에서는 작동하지 않음.

### ISSUE THREAD

**Issue by soso3055** [NyangBotLab/DBManager_deploy#4]
녹스와 같은 에뮬레이터에서는 작동하지 않음.

알림 자체를 읽어오지 못하는것 같습니다.

해당 문제가 해결 될 수 있을까요?

**Comment by saroro1** [comment]
현재 녹스에서 잘 확인되는 것을 확인했습니다. 안드버전 및 api 레거시인지 2인지 등등 정보를 더 알려주십시오

**Comment by saroro1** [comment]
확인결과 메신저봇 레거시에선 잘 되네 api2에서 안되는 현상이 있음......

바렛이 일하면 해결가능
