### ISSUE TITLE
not working if I mention the bot

### ISSUE THREAD

**Issue by taeseong14** [NyangBotLab/DBManager_deploy#5]
봇을 멘션한 메시지에 chat.source로 접근을 못함

**Comment by taeseong14** [comment]
getNextChat도 다음챗이 봇이 보낸 메시지라면 작동 안하는데 이건 당연한건가

**Comment by saroro1** [comment]
자기 자신은 friends 테이블에 없고  pb파일에 따로 있습니다. pb읽는것만 만들면 되긴 하는데 일단 won't fix로 두겠습니다
