### ISSUE TITLE
[BUG] kakaotalk v10.4.2 DBanager error

### ISSUE THREAD

**Issue by jaehyun1122** [NyangBotLab/DBManager_deploy#8]
네

### 현재 동작:
카카오톡 버전 10.3.7에서는 잘 작동 하였으나 10.4.2버전부터 오류가 로그에 도배를 하며 작동을 하지 않습니다.

### 기대하는 동작:
오류 없이 작동하는것(?)

### 재현 방법:
컴퓨터 윈도우 11 > 녹스앱플레이어 > 안드로이드9에서 카톡버전 10.4.2에서 아래와 같이 오류가 나타나면서 동작을 안함

1
javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/decrypt/decrypt-new.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/decrypt/decrypt.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/decrypt/decrypt.js:1 (decrypt)
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1 (T)
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1 (K)
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/db_util/src/db_utils.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/DBManager/DBManager.js:1

### 기타:
10.4.2를 제외하고는 잘 작동하는 것 같다

**Comment by jaehyun1122** [comment]
> ### 현재 동작:
> 카카오톡 버전 10.3.7에서는 잘 작동 하였으나 10.4.2버전부터 오류가 로그에 도배를 하며 작동을 하지 않습니다.
> 
> ### 기대하는 동작:
> 오류 없이 작동하는것(?)
> 
> ### 재현 방법:
> 컴퓨터 윈도우 11 > 녹스앱플레이어 > 안드로이드9에서 카톡버전 10.4.2에서 아래와 같이 오류가 나타나면서 동작을 안함
> 1 javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/decrypt/decrypt-new.js:1 at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/decrypt/decrypt.js:1 at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/decrypt/decrypt.js:1 (decrypt) at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1 (T) at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1 (K) at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1 at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/mapper.js:1 at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/db_util/src/db_utils.js:1 at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/DBManager/DBManager.js:1
> 
> ### 환경:
> ### 기타:
> 10.4.2를 제외하고는 잘 작동하는 것 같다

**Comment by jaehyun1122** [comment]
- OS: 안드로이드 9
- 메봇/채자봇: 메봇
- 메봇 버전: 0.7.29a/79
- 모듈 버전: 2.4.0

**Comment by jaehyun1122** [comment]
> * OS: 안드로이드 9
> * 메봇/채자봇: 메봇
> * 메봇 버전: 0.7.29a/92
> * 모듈 버전: 2.4.0

**Comment by saroro1** [comment]
[새 복호화 함수 제작](https://github.com/NyangBotLab/DBManager_deploy/tree/478b7ed8d69d823cbab13a9e6256581e93869aa3)
패치했으니 확인해보세요
