### ISSUE TITLE
[BUG] 카톡 10.4.2 / 모듈버전 1.4.1 이슈

### ISSUE THREAD

**Issue by jaehyun1122** [NyangBotLab/DBManager_deploy#9]
### 현재 동작:
오류를 뿜으면서 작동안함 :(

### 재현 방법:
모듈버전 1.4.1에서 다음과 같이 오류가 발생하며 작동하지 않음

Runtime Error(kakao_DB)
TypeError: TypeError: redeclaration of const T. (file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/index.js#1)	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/mapper/index.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/utils/index.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/classes/channel/channel-session.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/classes/channel/channel-session-manager.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/classes/channel/channel.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/classes/channel/index.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/classes/index.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/DBManager/DBManager.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/DBManager/index.js:1
	at file:/storage/emulated/0/msgbot/global_modules/DBManager_deploy-2/modules/DBManager/index.js:1
	at kakao_DB:21

### 환경:

특이사항 : 윈도우 11 녹스앱플레이어에서 사용중
- OS: 안드로이드 9
- 메봇/채자봇: 메봇
- 메봇 버전: 0.7.29a/92
- 모듈 버전: 2.4.1

**Comment by jaehyun1122** [comment]
사용자가 잘못함 :(

**Comment by jaehyun1122** [comment]
ㅈㅅ 합니다 모듈 오류 맞아요

**Comment by vientorepublic** [comment]
버전을 2.4.1과 1.4.1로 상반되게 작성하셨는데, 하나로 정정 부탁 드립니다.

**Comment by jaehyun1122** [comment]
해결됨
